default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>

development:
  <<: *default
  database: studypad_development
  

test:
  <<: *default
  database: studypad_test

production:
  url: <%= ENV['DATABASE_URL'] %>
